### PR TITLE
389 consistent design and bug fixes

### LINKED ISSUE #389: consistent Design and bug fixes
- add consistent design to all boxes etc
- fix text being uppercase
- fix idea card  responsive
- generel design bug fixes

### PR DESCRIPTION
**Pull request by LetsPoke**
refactor all the style attributes 

closes #389

### CODE REVIEW

File: hms-app/src/common/styles.ts [hunk 1]
```diff
@@ -44,7 +63,7 @@ export const styles = createStyles((theme) => ({
     display: 'block',
     lineHeight: 1,
     padding: '8px 12px',
-    borderRadius: theme.radius.sm,
+    borderRadius: borderRadius / 2,
```
Comment (verzano) [inline hms-app/src/common/styles.ts:66]: I would specify this as a constant as well outside of here

File: hms-app/src/common/types.ts [hunk 2]
```diff
@@ -10,6 +10,13 @@ export enum HackathonDetailsType {
   FullInfo = 'FULLINFO',
 }
 
+export enum IdeaCardTypes {
+  Owner = 'OWNER',
+  Admin = 'ADMIN',
+  Voting = 'VOTING',
+  Other = 'OTHER',
```
Comment (verzano) [inline hms-app/src/common/types.ts:17]: other seems a bit too... all inclusive.  We could probably be a bit more specific
