### PR TITLE
consistent hackathon details and fix presentations

### LINKED ISSUE #391: check all text for responsivness
check all text blocks for responsivness for example idea description in presentations page, when not in fullscreen

### PR DESCRIPTION
**Pull request by LetsPoke**
closes #391

### CODE REVIEW

File: hms-app/src/components/card-details/HackathonDetails.tsx [hunk 1]
```diff
@@ -253,12 +253,15 @@ export default function HackathonDetails(props: IProps) {
...
-            <h2>All Ideas ({hackathonData.ideas?.length})</h2>
+            <Text align={'center'} className={classes.title}>
+              Title: {hackathonData.title}
+            </Text>
+            <Text align={'center'} className={classes.title}>
+              Start date: {new Date(hackathonData.startDate).toLocaleDateString()}
+            </Text>
+            <Text align={'center'} className={classes.title}>
+              End date: {new Date(hackathonData.endDate).toLocaleDateString()}
+            </Text>
```
Comment (verzano) [inline hms-app/src/components/card-details/HackathonDetails.tsx:264]: this is duplicated, it could be extracted to it's own class

**Review by verzano — APPROVED** [review]
